"""Maintain the generated summary row at the foot of data/instruments.csv.

The novelty claim needs one number, and the row count is not it: the evidence
is not uniform across the instruments. Eleven have the absence of a time axis
established by TERM COUNT - which a reviewer can re-run - and five rest on
qualitative reading of the evidence base. Headline sentences use eleven.

The summary is written into the data file rather than kept in prose so that it
cannot drift from the rows it describes. `refresh()` recomputes it;
`tests/test_registers.py` fails if the stored line disagrees with the rows.
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INSTRUMENTS_CSV = REPO_ROOT / "data" / "instruments.csv"

SUMMARY_ID = "SUMMARY"
SUMMARY_METHOD = "generated_summary"

# Methods that rest on an actual term count, and therefore on something a
# reviewer can reproduce.
COUNTED_METHODS = (
    "full_text_term_count",
    "full_text_term_count_aggregated_over_cluster",
    "partial_read_full_term_search",
    "term_search_only",
)
QUALITATIVE_METHOD = "qualitative_no_term_count"


def read_rows(path: Path = INSTRUMENTS_CSV) -> tuple[list[str], list[dict[str, str]]]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        assert reader.fieldnames is not None
        return list(reader.fieldnames), list(reader)


def instrument_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    """The real instruments: everything except the generated summary row."""
    return [r for r in rows if r["id"] != SUMMARY_ID]


def tally(rows: list[dict[str, str]]) -> tuple[int, int, Counter]:
    methods = Counter(r["count_method"] for r in instrument_rows(rows))
    counted = sum(methods[m] for m in COUNTED_METHODS)
    qualitative = methods[QUALITATIVE_METHOD]
    return counted, qualitative, methods


def summary_note(rows: list[dict[str, str]]) -> str:
    counted, qualitative, methods = tally(rows)
    breakdown = ", ".join(
        f"{methods[m]} {m}" for m in COUNTED_METHODS if methods[m]
    )
    return (
        f"counted={counted}; qualitative={qualitative}. "
        f"{counted} instruments where the absence of a time axis for containment was established "
        f"by term count ({breakdown}), and {qualitative} more by qualitative reading of the "
        f"evidence base. Headline sentences use {counted}, because that is the number a reviewer "
        f"can re-run; all {counted + qualitative} rows stay in the data. The figures of ten, "
        f"twelve and fourteen instruments that appear in the evidence base are stale - they date "
        f"from earlier drafts and were never reconciled."
    )


def build_summary_row(fields: list[str], rows: list[dict[str, str]]) -> dict[str, str]:
    row = {field: "" for field in fields}
    row.update({
        "id": SUMMARY_ID,
        "instrument": "generated summary - not an instrument",
        "version_or_date": "regenerated by src/instruments_summary.py",
        "object_protected": "",
        "scope_note": summary_note(rows),
        "n_time_axis_present": "FALSE",
        "source_ref": "derived from the instrument rows above",
        "count_method": SUMMARY_METHOD,
    })
    return row


def refresh(path: Path = INSTRUMENTS_CSV) -> dict[str, str]:
    fields, rows = read_rows(path)
    instruments = instrument_rows(rows)
    summary = build_summary_row(fields, instruments)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(instruments + [summary])
    return summary


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    summary = refresh()
    if not args.quiet:
        counted, qualitative, _ = tally(read_rows()[1])
        print(f"instruments: {counted} counted, {qualitative} qualitative, "
              f"{counted + qualitative} rows")
        print(summary["scope_note"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
